### ISSUE TITLE
BItcoin transaction

### ISSUE THREAD

**Issue by ivofernandes** [mrtnetwork/bitcoin_base#1]
I'm trying to use this lib as part of a crypto wallet but got stuck in this error:

      final changeAddr = P2pkhAddress(
        address: 'tb1qhtnl5n66h242e580h9sdkz8edjk335j9mrzyxj',
      );

Seems like tb1qhtnl5n66h242e580h9sdkz8edjk335j9mrzyxj has an l that is not in base58 alphabet

Added the test in this fork
https://github.com/ivofernandes/bitcoin_base/blob/main/test/transaction_test.dart

The problem is in the blockchain_utils but at the same time the project is not using the last version of blockchain_utils

Can you help with this?

**Comment by mrtnetwork** [comment]
> I'm trying to use this lib as part of a crypto wallet but got stuck in this error:
> 
> ```
>   final changeAddr = P2pkhAddress(
>     address: 'tb1qhtnl5n66h242e580h9sdkz8edjk335j9mrzyxj',
>   );
> ```
> 
> Seems like tb1qhtnl5n66h242e580h9sdkz8edjk335j9mrzyxj has an l that is not in base58 alphabet
> 
> Added the test in this fork https://github.com/ivofernandes/bitcoin_base/blob/main/test/transaction_test.dart
> 
> The problem is in the blockchain_utils but at the same time the project is not using the last version of blockchain_utils
> 
> Can you help with this?

I update package tomorrow,```tb1qhtnl5n66h242e580h9sdkz8edjk335j9mrzyxj``` but  address is p2wsh
u must use P2wshAddress 
```
P2wshAddress(address: "tb1qhtnl5n66h242e580h9sdkz8edjk335j9mrzyxj");
```

**Comment by mrtnetwork** [comment]
> I'm trying to use this lib as part of a crypto wallet but got stuck in this error:
> 
> ```
>   final changeAddr = P2pkhAddress(
>     address: 'tb1qhtnl5n66h242e580h9sdkz8edjk335j9mrzyxj',
>   );
> ```
> 
> Seems like tb1qhtnl5n66h242e580h9sdkz8edjk335j9mrzyxj has an l that is not in base58 alphabet
> 
> Added the test in this fork https://github.com/ivofernandes/bitcoin_base/blob/main/test/transaction_test.dart
> 
> The problem is in the blockchain_utils but at the same time the project is not using the last version of blockchain_utils
> 
> Can you help with this?

I have updated both [bitcoin_base](https://pub.dev/packages/bitcoin_base), [blockchain_utils](https://pub.dev/packages/blockchain_utils) packages and now you can obtain them from Pub.
