### ISSUE TITLE
Transferring BTC from untweakked taproot to tweaked taproot fails for some reason

### ISSUE THREAD

**Issue by kicksomedust** [mrtnetwork/bitcoin_base#12]
/*
  Scenario: derive two taproot addresses from the same private and public key:
  one with tweak == false, the other with tweak == true.
  Then transfer some btc to tweaked address from a faucet and 
  after that run this code: it should transfer btc to the untweaked taproot address.
  When this is done, run this code again. btc should be transferred from the untweaked 
  taproot address to the tweaked taproot address. but the code produces an error:
  sendrawtransaction RPC error -26: {"code":-26,"message":"mandatory-script-verify-flag-failed (Invalid Schnorr signature)"}.
  Don't understand why, but I'm relatively new to this, so my suppositions may be flawed
*/

import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:bitcoin_base/bitcoin_base.dart';
import 'package:blockchain_utils/bip/bip/bip32/base/bip32_base.dart';
import 'package:blockchain_utils/bip/bip/bip32/slip10/bip32_slip10_secp256k1.dart';
import 'package:blockchain_utils/bip/bip/bip39/bip39_seed_generator.dart';
import 'package:blockchain_utils/bip/mnemonic/mnemonic.dart';
import 'package:blockchain_utils/utils/binary/utils.dart';
import 'package:test/test.dart';

    test("current", () async {
      void moveSome(
          dynamic provider,
          List<ElectrumUtxo> utxoFromServer,
          ECPrivate privKey,
          P2trAddress taprootAddressFrom,
          P2trAddress taprootAddressTo) async {
        ///
        const BitcoinNetwork testnet = BitcoinNetwork.testnet;

        List<UtxoWithAddress> utxos = [
          UtxoWithAddress(
              utxo: BitcoinUtxo(
                txHash: utxoFromServer[0].txId,
                value: utxoFromServer[0].value,
                vout: utxoFromServer[0].vout,
                scriptType: taprootAddressFrom.type,
              ),
              ownerDetails: UtxoAddressDetails(
                  publicKey: privKey.getPublic().toHex(),
                  address: taprootAddressFrom)),
        ];

        BigInt fee = BigInt.from(120);
        BigInt value = utxoFromServer[0].value - fee;
        BigInt total = utxoFromServer[0].value;

        expect(value + fee, total);

        final builder = BitcoinTransactionBuilder(

            outputs: [BitcoinOutput(address: taprootAddressTo, value: value)],
            fee: fee,
            network: testnet,
            enableRBF: true,
            utxos: utxos);

        final BtcTransaction tr =
            builder.buildTransaction((trDigest, utxo, publicKey, sighash) {
          if (publicKey == privKey.getPublic().toHex() && utxo.utxo.isP2tr()) {
            return privKey.signTapRoot(trDigest, sighash: sighash);
          }
          throw UnimplementedError();
        });

        final raw = tr.serialize();

        await provider
            .request(ElectrumBroadCastTransaction(transactionRaw: raw));
      }

      const BitcoinNetwork testnet = BitcoinNetwork.testnet;

      final service = await ElectrumSSLService.connect("blockstream.info:993");

      final provider = ElectrumApiProvider(service);

      final seed = Bip39SeedGenerator(Mnemonic.fromString(
              "word nurse twenty supreme surround ice neutral stem original engine mix transfer slogan sorry candy decrease lift space expose attack state outdoor hold portion"))
          .generate();

      final bip32 = Bip32Slip10Secp256k1.fromSeed(seed);

      final derivationForTaproot = bip32.derivePath("m/86'/0'/0'/0/1");
      final privateForTaproot =
          ECPrivate.fromBytes(derivationForTaproot.privateKey.raw);
      final publicForTaproot = privateForTaproot.getPublic();

      final tweakedTaproot = publicForTaproot.toTaprootAddress(tweak: true);
      print("tweak : true -> " + tweakedTaproot.toAddress(testnet).toString());
      final untweakedTaproot = publicForTaproot.toTaprootAddress(tweak: false);
      print(
          "tweak : false -> " + untweakedTaproot.toAddress(testnet).toString());

      List<ElectrumUtxo> tweakedUtxos =
          await provider.request(ElectrumScriptHashListUnspent(
        scriptHash: tweakedTaproot.pubKeyHash(),
        includeTokens: false,
      ));

      List<ElectrumUtxo> untweakedUtxos =
          await provider.request(ElectrumScriptHashListUnspent(
        scriptHash: untweakedTaproot.pubKeyHash(),
        includeTokens: false,
      ));

      expect(tweakedUtxos.isNotEmpty || untweakedUtxos.isNotEmpty, true);

      if ((tweakedUtxos.isNotEmpty &&
          (untweakedUtxos.isEmpty ||
              untweakedUtxos[0].value <= tweakedUtxos[0].value))) {
        //  move some to untweaked
        print("moving some from tweaked to untweaked");
        moveSome(provider, tweakedUtxos, privateForTaproot, tweakedTaproot,
            untweakedTaproot);
      } else if (untweakedUtxos.isNotEmpty &&
          (tweakedUtxos.isEmpty ||
              tweakedUtxos[0].value < untweakedUtxos[0].value)) {
        //  move some to tweaked
        print("moving some from untweaked to tweeaked");
        moveSome(provider, untweakedUtxos, privateForTaproot, untweakedTaproot,
            tweakedTaproot);
      }
    }, skip: false);

**Comment by mrtnetwork** [comment]
> /* Scenario: derive two taproot addresses from the same private and public key: one with tweak == false, the other with tweak == true. Then transfer some btc to tweaked address from a faucet and after that run this code: it should transfer btc to the untweaked taproot address. When this is done, run this code again. btc should be transferred from the untweaked taproot address to the tweaked taproot address. but the code produces an error: sendrawtransaction RPC error -26: {"code":-26,"message":"mandatory-script-verify-flag-failed (Invalid Schnorr signature)"}. Don't understand why, but I'm relatively new to this, so my suppositions may be flawed */
> 
> import 'dart:async'; import 'dart:convert'; import 'dart:io';
> 
> import 'package:bitcoin_base/bitcoin_base.dart'; import 'package:blockchain_utils/bip/bip/bip32/base/bip32_base.dart'; import 'package:blockchain_utils/bip/bip/bip32/slip10/bip32_slip10_secp256k1.dart'; import 'package:blockchain_utils/bip/bip/bip39/bip39_seed_generator.dart'; import 'package:blockchain_utils/bip/mnemonic/mnemonic.dart'; import 'package:blockchain_utils/utils/binary/utils.dart'; import 'package:test/test.dart';
> 
> ```
> test("current", () async {
>   void moveSome(
>       dynamic provider,
>       List<ElectrumUtxo> utxoFromServer,
>       ECPrivate privKey,
>       P2trAddress taprootAddressFrom,
>       P2trAddress taprootAddressTo) async {
>     ///
>     const BitcoinNetwork testnet = BitcoinNetwork.testnet;
> 
>     List<UtxoWithAddress> utxos = [
>       UtxoWithAddress(
>           utxo: BitcoinUtxo(
>             txHash: utxoFromServer[0].txId,
>             value: utxoFromServer[0].value,
>             vout: utxoFromServer[0].vout,
>             scriptType: taprootAddressFrom.type,
>           ),
>           ownerDetails: UtxoAddressDetails(
>               publicKey: privKey.getPublic().toHex(),
>               address: taprootAddressFrom)),
>     ];
> 
>     BigInt fee = BigInt.from(120);
>     BigInt value = utxoFromServer[0].value - fee;
>     BigInt total = utxoFromServer[0].value;
> 
>     expect(value + fee, total);
> 
>     final builder = BitcoinTransactionBuilder(
> 
>         outputs: [BitcoinOutput(address: taprootAddressTo, value: value)],
>         fee: fee,
>         network: testnet,
>         enableRBF: true,
>         utxos: utxos);
> 
>     final BtcTransaction tr =
>         builder.buildTransaction((trDigest, utxo, publicKey, sighash) {
>       if (publicKey == privKey.getPublic().toHex() && utxo.utxo.isP2tr()) {
>         return privKey.signTapRoot(trDigest, sighash: sighash);
>       }
>       throw UnimplementedError();
>     });
> 
>     final raw = tr.serialize();
> 
>     await provider
>         .request(ElectrumBroadCastTransaction(transactionRaw: raw));
>   }
> 
>   const BitcoinNetwork testnet = BitcoinNetwork.testnet;
> 
>   final service = await ElectrumSSLService.connect("blockstream.info:993");
> 
>   final provider = ElectrumApiProvider(service);
> 
>   final seed = Bip39SeedGenerator(Mnemonic.fromString(
>           "word nurse twenty supreme surround ice neutral stem original engine mix transfer slogan sorry candy decrease lift space expose attack state outdoor hold portion"))
>       .generate();
> 
>   final bip32 = Bip32Slip10Secp256k1.fromSeed(seed);
> 
>   final derivationForTaproot = bip32.derivePath("m/86'/0'/0'/0/1");
>   final privateForTaproot =
>       ECPrivate.fromBytes(derivationForTaproot.privateKey.raw);
>   final publicForTaproot = privateForTaproot.getPublic();
> 
>   final tweakedTaproot = publicForTaproot.toTaprootAddress(tweak: true);
>   print("tweak : true -> " + tweakedTaproot.toAddress(testnet).toString());
>   final untweakedTaproot = publicForTaproot.toTaprootAddress(tweak: false);
>   print(
>       "tweak : false -> " + untweakedTaproot.toAddress(testnet).toString());
> 
>   List<ElectrumUtxo> tweakedUtxos =
>       await provider.request(ElectrumScriptHashListUnspent(
>     scriptHash: tweakedTaproot.pubKeyHash(),
>     includeTokens: false,
>   ));
> 
>   List<ElectrumUtxo> untweakedUtxos =
>       await provider.request(ElectrumScriptHashListUnspent(
>     scriptHash: untweakedTaproot.pubKeyHash(),
>     includeTokens: false,
>   ));
> 
>   expect(tweakedUtxos.isNotEmpty || untweakedUtxos.isNotEmpty, true);
> 
>   if ((tweakedUtxos.isNotEmpty &&
>       (untweakedUtxos.isEmpty ||
>           untweakedUtxos[0].value <= tweakedUtxos[0].value))) {
>     //  move some to untweaked
>     print("moving some from tweaked to untweaked");
>     moveSome(provider, tweakedUtxos, privateForTaproot, tweakedTaproot,
>         untweakedTaproot);
>   } else if (untweakedUtxos.isNotEmpty &&
>       (tweakedUtxos.isEmpty ||
>           tweakedUtxos[0].value < untweakedUtxos[0].value)) {
>     //  move some to tweaked
>     print("moving some from untweaked to tweeaked");
>     moveSome(provider, untweakedUtxos, privateForTaproot, untweakedTaproot,
>         tweakedTaproot);
>   }
> }, skip: false);
> ```
```
final tweakedTaproot = publicForTaproot.toTaprootAddress(tweak: true);
```
 Which version introduced the `tweak` option? I don’t recall `toTaprootAddress` supporting this parameter.

**Comment by kicksomedust** [comment]
Sorry, I may have posted this to the wrong place.
This parameter has been introduced in the very first version after the fork

**Comment by mrtnetwork** [comment]
> Sorry, I may have posted this to the wrong place. This parameter has been introduced in the very first version after the fork

GL
