### ISSUE TITLE
More detailed tests

### ISSUE THREAD

**Issue by ivofernandes** [mrtnetwork/bitcoin_base#2]
Is it possible for you to add a test that picks a seedphrase and some transaction to generate and hexadecimal?

I found this tests very complicated to follow as they pick private key wif, then addresses and seems like all was pre generated
https://github.com/mrtnetwork/bitcoin_base/blob/main/test/p2kh_tr_test.dart

Not sure if is clear what I mean, I can try to create a test if it's easier

**Comment by mrtnetwork** [comment]
> Is it possible for you to add a test that picks a seedphrase and some transaction to generate and hexadecimal?
> 
> I found this tests very complicated to follow as they pick private key wif, then addresses and seems like all was pre generated https://github.com/mrtnetwork/bitcoin_base/blob/main/test/p2kh_tr_test.dart
> 
> Not sure if is clear what I mean, I can try to create a test if it's easier

Hi, please look at https://github.com/mrtnetwork/bitcoin_base/tree/main/example/spending_with_scripts and https://github.com/mrtnetwork/bitcoin_base/tree/main/example/spending_with_transaction_builder to see how it works find out

**Comment by ivofernandes** [comment]
Thanks :)

That transaction builder test is really amazing, thanks for your amazing work
