### ISSUE TITLE
将bitcoin_base库打包在SDK中，运行没有报错，但是将SDK引入app，运行APP出错

### ISSUE THREAD

**Issue by whrime** [mrtnetwork/bitcoin_base#4]
报错内容如下，想请问有遇到类型情况的吗，如何解决；
尝试flutter clean，之后flutter pub get；没有解决

`/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/address/segwit_address.dart:49:29: Error: The getter '$1' isn't defined for the class 'Tuple<int, List<in
t>>'.
 - 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
 - 'List' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named '$1'.
    final version = convert.$1;
                            ^^
/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/address/segwit_address.dart:53:43: Error: The getter '$2' isn't defined for the class 'Tuple<int, List<in
t>>'.
 - 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
 - 'List' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named '$2'.
    return BytesUtils.toHexString(convert.$2);
                                          ^^
/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/input.dart:65:18: Error: The getter '$2' isn't defined for the class 'Tuple<int, int>'.
 - 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named '$2'.
    cursor += vi.$2;
                 ^^
/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/input.dart:65:12: Error: A value of type 'num' can't be assigned to a variable of type 'int'.     
    cursor += vi.$2;
           ^
/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/input.dart:66:72: Error: The getter '$1' isn't defined for the class 'Tuple<int, int>'.
 - 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named '$1'.
    List<int> unlockingScript = txInputRaw.sublist(cursor, cursor + vi.$1);
                                                                       ^^
/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/input.dart:66:67: Error: The argument type 'num' can't be assigned to the parameter type 'int?'.  
    List<int> unlockingScript = txInputRaw.sublist(cursor, cursor + vi.$1);
                                                                  ^
/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/input.dart:67:18: Error: The getter '$1' isn't defined for the class 'Tuple<int, int>'.
 - 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named '$1'.
    cursor += vi.$1;
                 ^^
/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/input.dart:67:12: Error: A value of type 'num' can't be assigned to a variable of type 'int'.
    cursor += vi.$1;
           ^
/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/output.dart:43:18: Error: The getter '$2' isn't defined for the class 'Tuple<int, int>'.
 - 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named '$2'.
    cursor += vi.$2;
                 ^^
/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/output.dart:43:12: Error: A value of type 'num' can't be assigned to a variable of type 'int'.    
    cursor += vi.$2;
           ^
/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/output.dart:44:68: Error: The getter '$1' isn't defined for the class 'Tuple<int, int>'.
 - 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named '$1'.
    List<int> lockScript = txoutputraw.sublist(cursor, cursor + vi.$1);
                                                                   ^^
/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/output.dart:44:63: Error: The argument type 'num' can't be assigned to the parameter type 'int?'. 
    List<int> lockScript = txoutputraw.sublist(cursor, cursor + vi.$1);
                                                              ^
/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/output.dart:45:18: Error: The getter '$1' isn't defined for the class 'Tuple<int, int>'.
 - 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named '$1'.
    cursor += vi.$1;
                 ^^
/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/output.dart:45:12: Error: A value of type 'num' can't be assigned to a variable of type 'int'.    
    cursor += vi.$1;
           ^
/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/script.dart:72:34: Error: The getter '$1' isn't defined for the class 'Tuple<int, int>'.
 - 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named '$1'.
        int dataSize = viAndSize.$1;
                                 ^^
/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/script.dart:73:30: Error: The getter '$2' isn't defined for the class 'Tuple<int, int>'.
 - 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named '$2'.
        int size = viAndSize.$2;
                             ^^
/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/transaction.dart:76:18: Error: The getter '$2' isn't defined for the class 'Tuple<int, int>'.     
 - 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named '$2'.
    cursor += vi.$2;
                 ^^
/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/transaction.dart:76:12: Error: A value of type 'num' can't be assigned to a variable of type 'int'
.
    cursor += vi.$2;
           ^
/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/transaction.dart:79:36: Error: The getter '$1' isn't defined for the class 'Tuple<int, int>'.     
 - 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named '$1'.
    for (int index = 0; index < vi.$1; index++) {
                                   ^^
/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/transaction.dart:89:21: Error: The getter '$2' isn't defined for the class 'Tuple<int, int>'.     
 - 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named '$2'.
    cursor += viOut.$2;
                    ^^
/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/transaction.dart:89:12: Error: A value of type 'num' can't be assigned to a variable of type 'int'
.
    cursor += viOut.$2;
           ^
/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/transaction.dart:90:39: Error: The getter '$1' isn't defined for the class 'Tuple<int, int>'.     
 - 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named '$1'.
    for (int index = 0; index < viOut.$1; index++) {
                                      ^^
/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/crypto/keypair/ec_private.dart:24:39: Error: The getter '$1' isn't defined for the class 'Tuple<List<int>, PubKey
Modes>'.
 - 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
 - 'List' is from 'dart:core'.
 - 'PubKeyModes' is from 'package:blockchain_utils/bip/address/p2pkh_addr.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/bip/address/p2pkh_addr.dart'). 
Try correcting the name to the name of an existing getter, or defining a getter or field named '$1'.
    return ECPrivate.fromBytes(decode.$1);
                                      ^^
/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/address/validate.dart:74:27: Error: The getter '$1' isn't defined for the class 'Tuple<List<int>, List<in
t>>'.
 - 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
 - 'List' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named '$1'.
    if (bytesEqual(decode.$1, netVersion)) {
                          ^^
/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/address/validate.dart:75:21: Error: The getter '$2' isn't defined for the class 'Tuple<List<int>, List<in
t>>'.
 - 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
 - 'List' is from 'dart:core'.
Try correcting the name to the name of an existing getter, or defining a getter or field named '$2'.
      return decode.$2;
                    ^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script 'D:\workspace\git_soft\flutter\packages\flutter_tools\gradle\src\main\groovy\flutter.groovy' line: 1297

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\workspace\git_soft\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
`

**Comment by mrtnetwork** [comment]
> 报错内容如下，想请问有遇到类型情况的吗，如何解决； 尝试flutter clean，之后flutter pub get；没有解决
> 
> `/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/address/segwit_address.dart:49:29: Error: The getter '$1' isn't defined for the class 'Tuple<int, List>'.
> 
> * 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
> * 'List' is from 'dart:core'.
>   Try correcting the name to the name of an existing getter, or defining a getter or field named '$1'.
>   final version = convert.$1;
>   ^^
>   /C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/address/segwit_address.dart:53:43: Error: The getter '$2' isn't defined for the class 'Tuple<int, List>'.
> * 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
> * 'List' is from 'dart:core'.
>   Try correcting the name to the name of an existing getter, or defining a getter or field named '$2'.
>   return BytesUtils.toHexString(convert.$2);
>   ^^
>   /C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/input.dart:65:18: Error: The getter '$2' isn't defined for the class 'Tuple<int, int>'.
> * 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
>   Try correcting the name to the name of an existing getter, or defining a getter or field named '$2'.
>   cursor += vi.$2;
>   ^^
>   /C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/input.dart:65:12: Error: A value of type 'num' can't be assigned to a variable of type 'int'.
>   cursor += vi.$2;
>   ^
>   /C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/input.dart:66:72: Error: The getter '$1' isn't defined for the class 'Tuple<int, int>'.
> * 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
>   Try correcting the name to the name of an existing getter, or defining a getter or field named '$1'.
>   List unlockingScript = txInputRaw.sublist(cursor, cursor + vi.$1);
>   ^^
>   /C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/input.dart:66:67: Error: The argument type 'num' can't be assigned to the parameter type 'int?'.
>   List unlockingScript = txInputRaw.sublist(cursor, cursor + vi.$1);
>   ^
>   /C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/input.dart:67:18: Error: The getter '$1' isn't defined for the class 'Tuple<int, int>'.
> * 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
>   Try correcting the name to the name of an existing getter, or defining a getter or field named '$1'.
>   cursor += vi.$1;
>   ^^
>   /C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/input.dart:67:12: Error: A value of type 'num' can't be assigned to a variable of type 'int'.
>   cursor += vi.$1;
>   ^
>   /C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/output.dart:43:18: Error: The getter '$2' isn't defined for the class 'Tuple<int, int>'.
> * 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
>   Try correcting the name to the name of an existing getter, or defining a getter or field named '$2'.
>   cursor += vi.$2;
>   ^^
>   /C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/output.dart:43:12: Error: A value of type 'num' can't be assigned to a variable of type 'int'.
>   cursor += vi.$2;
>   ^
>   /C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/output.dart:44:68: Error: The getter '$1' isn't defined for the class 'Tuple<int, int>'.
> * 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
>   Try correcting the name to the name of an existing getter, or defining a getter or field named '$1'.
>   List lockScript = txoutputraw.sublist(cursor, cursor + vi.$1);
>   ^^
>   /C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/output.dart:44:63: Error: The argument type 'num' can't be assigned to the parameter type 'int?'.
>   List lockScript = txoutputraw.sublist(cursor, cursor + vi.$1);
>   ^
>   /C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/output.dart:45:18: Error: The getter '$1' isn't defined for the class 'Tuple<int, int>'.
> * 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
>   Try correcting the name to the name of an existing getter, or defining a getter or field named '$1'.
>   cursor += vi.$1;
>   ^^
>   /C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/output.dart:45:12: Error: A value of type 'num' can't be assigned to a variable of type 'int'.
>   cursor += vi.$1;
>   ^
>   /C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/script.dart:72:34: Error: The getter '$1' isn't defined for the class 'Tuple<int, int>'.
> * 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
>   Try correcting the name to the name of an existing getter, or defining a getter or field named '$1'.
>   int dataSize = viAndSize.$1;
>   ^^
>   /C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/script.dart:73:30: Error: The getter '$2' isn't defined for the class 'Tuple<int, int>'.
> * 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
>   Try correcting the name to the name of an existing getter, or defining a getter or field named '$2'.
>   int size = viAndSize.$2;
>   ^^
>   /C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/transaction.dart:76:18: Error: The getter '$2' isn't defined for the class 'Tuple<int, int>'.
> * 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
>   Try correcting the name to the name of an existing getter, or defining a getter or field named '$2'.
>   cursor += vi.$2;
>   ^^
>   /C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/transaction.dart:76:12: Error: A value of type 'num' can't be assigned to a variable of type 'int'
>   .
>   cursor += vi.$2;
>   ^
>   /C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/transaction.dart:79:36: Error: The getter '$1' isn't defined for the class 'Tuple<int, int>'.
> * 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
>   Try correcting the name to the name of an existing getter, or defining a getter or field named '$1'.
>   for (int index = 0; index < vi.$1; index++) {
>   ^^
>   /C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/transaction.dart:89:21: Error: The getter '$2' isn't defined for the class 'Tuple<int, int>'.
> * 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
>   Try correcting the name to the name of an existing getter, or defining a getter or field named '$2'.
>   cursor += viOut.$2;
>   ^^
>   /C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/transaction.dart:89:12: Error: A value of type 'num' can't be assigned to a variable of type 'int'
>   .
>   cursor += viOut.$2;
>   ^
>   /C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/script/transaction.dart:90:39: Error: The getter '$1' isn't defined for the class 'Tuple<int, int>'.
> * 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
>   Try correcting the name to the name of an existing getter, or defining a getter or field named '$1'.
>   for (int index = 0; index < viOut.$1; index++) {
>   ^^
>   /C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/crypto/keypair/ec_private.dart:24:39: Error: The getter '$1' isn't defined for the class 'Tuple<List, PubKey
>   Modes>'.
> * 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
> * 'List' is from 'dart:core'.
> * 'PubKeyModes' is from 'package:blockchain_utils/bip/address/p2pkh_addr.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/bip/address/p2pkh_addr.dart').
>   Try correcting the name to the name of an existing getter, or defining a getter or field named '$1'.
>   return ECPrivate.fromBytes(decode.$1);
>   ^^
>   /C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/address/validate.dart:74:27: Error: The getter '$1' isn't defined for the class 'Tuple<List, List>'.
> * 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
> * 'List' is from 'dart:core'.
>   Try correcting the name to the name of an existing getter, or defining a getter or field named '$1'.
>   if (bytesEqual(decode.$1, netVersion)) {
>   ^^
>   /C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bitcoin_base-2.0.1/lib/src/bitcoin/address/validate.dart:75:21: Error: The getter '$2' isn't defined for the class 'Tuple<List, List>'.
> * 'Tuple' is from 'package:blockchain_utils/tuple/tuple.dart' ('/C:/Users/86130/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/blockchain_utils-1.4.1/lib/tuple/tuple.dart').
> * 'List' is from 'dart:core'.
>   Try correcting the name to the name of an existing getter, or defining a getter or field named '$2'.
>   return decode.$2;
>   ^^
>   Target kernel_snapshot failed: Exception
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
>   Script 'D:\workspace\git_soft\flutter\packages\flutter_tools\gradle\src\main\groovy\flutter.groovy' line: 1297
> * What went wrong:
>   Execution failed for task ':app:compileFlutterBuildDebug'.
> 
> > Process 'command 'D:\workspace\git_soft\flutter\bin\flutter.ba,t'' finished with non-zero exit value 1
> 
> * Try:
> 
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> > Get more help at https://help.gradle.org.
> > `
HI
Please be informed that the Dart SDK versions for 'bitcoin_base' and 'blockchain_utils' have been downgraded to version 2.5. To ensure the compatibility and optimal performance of your project, we recommend cleaning your project and updating to the latest versions available on pub.dev.
