### ISSUE TITLE
Getting bitcoin address type from address

### ISSUE THREAD

**Issue by Rimantovas** [mrtnetwork/bitcoin_base#5]
I think it would be good to implement an helper method that given an address string returns the right BitcoinAddress class

**Comment by mrtnetwork** [comment]
> I think it would be good to implement an helper method that given an address string returns the right BitcoinAddress class

I've been working on it, and I'm excited to share that a good update is on the way :)

**Comment by Rimantovas** [comment]
Great to hear. Also, are there any plans for supporting RPC calls instead of explorer API's?

**Comment by mrtnetwork** [comment]
> Great to hear. Also, are there any plans for supporting RPC calls instead of explorer API's?
now plugin support Electrum API

```
Added support for electrum api
Added support for BitcoinSV network
Introduced classes for improved network address handling
Implemented functionalities to create, sign, spend, mint, and burn Bitcoin Cash Tokens (FT, NFT tokens)
Implemented a class for creating the Bitcoin Cash Metadata Registry (BCMR).
Utilized BIP69 ordering for enhanced transaction sorting

```
