### ISSUE TITLE
needs hourFee

### ISSUE THREAD

**Issue by leeway1208** [mrtnetwork/bitcoin_base#6]
Pls provide hourFee in getNetworkFeeRate function. Thanks~~

**Comment by mrtnetwork** [comment]
> Pls provide hourFee in getNetworkFeeRate function. Thanks~~

hi, hourFee? i don't know what is that.

**Comment by leeway1208** [comment]
{"fastestFee":31,"halfHourFee":29,"hourFee":27,"economyFee":14,"minimumFee":7}
https://mempool.space/api/v1/fees/recommended
![image](https://github.com/mrtnetwork/bitcoin_base/assets/8113938/ebd64531-f8fb-489d-ac58-faf883ceb4d2)
hi bro. I mean add all the feerate types, now we only have fastestFee,halfHourFee and minimumFee.

**Comment by mrtnetwork** [comment]
> {"fastestFee":31,"halfHourFee":29,"hourFee":27,"economyFee":14,"minimumFee":7} https://mempool.space/api/v1/fees/recommended ![image](https://private-user-images.githubusercontent.com/8113938/326168936-ebd64531-f8fb-489d-ac58-faf883ceb4d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NDYyNjgsIm5iZiI6MTcxNDY0NTk2OCwicGF0aCI6Ii84MTEzOTM4LzMyNjE2ODkzNi1lYmQ2NDUzMS1mOGZiLTQ4OWQtYWM1OC1mYWY4ODNjZWI0ZDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDJUMTAzMjQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzFhNjhmYzdhOWZhZGVhZjg3MWI5MmE2MjE1ZDIxNmRiNDQxYzY3N2E0MmQ4MTNiOGI2ZmI0MmIxZTQwODE4YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qDCV2zgK0qKWOifbh0jXpXYTMYP2J8jouPNf4SO6e9I) hi bro. I mean add all the feerate types, now we only have fastestFee,halfHourFee and minimumFee.

I added this feature to mempool api, you can importing  repository from Github, I publish in pub.dev after some other feature or change
