### ISSUE TITLE
sign psbt

### ISSUE THREAD

**Issue by leeway1208** [mrtnetwork/bitcoin_base#7]
Hello~ Is there a way to sign psbt with ECPrivate, or convert psbt to txDigest? Thanks.

**Comment by mrtnetwork** [comment]
> Hello~ Is there a way to sign psbt with ECPrivate, or convert psbt to txDigest? Thanks.

pbs I am not familiar with this, can you give me the documents?

**Comment by leeway1208** [comment]
> > Hello~ Is there a way to sign psbt with ECPrivate, or convert psbt to txDigest? Thanks.
> 
> pbst? I am not familiar with this, can you give me the documents?

Hi, https://river.com/learn/what-are-partially-signed-bitcoin-transactions-psbts/ and https://github.com/bitcoin/bitcoin/blob/master/doc/psbt.md. I think it's a little difficult.

**Comment by mrtnetwork** [comment]
> > > Hello~ Is there a way to sign psbt with ECPrivate, or convert psbt to txDigest? Thanks.
> > 
> > 
> > pbst? I am not familiar with this, can you give me the documents?
> 
> Hi, https://river.com/learn/what-are-partially-signed-bitcoin-transactions-psbts/ and https://github.com/bitcoin/bitcoin/blob/master/doc/psbt.md. I think it's a little difficult.

I think you should take a look at the multi-signature transactions.https://github.com/mrtnetwork/bitcoin_base/blob/main/example/lib/global/old_examples/spending_with_transaction_builder/multi_sig_transactions.dart

**Comment by mrtnetwork** [comment]
> > > Hello~ Is there a way to sign psbt with ECPrivate, or convert psbt to txDigest? Thanks.
> > 
> > 
> > pbst? I am not familiar with this, can you give me the documents?
> 
> Hi, https://river.com/learn/what-are-partially-signed-bitcoin-transactions-psbts/ and https://github.com/bitcoin/bitcoin/blob/master/doc/psbt.md. I think it's a little difficult.


now package support PSBTV0/V2
